name: Cartify BE - CI (Build Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  be_build:
    name: Backend Build (Docker)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Cartify-BE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build BE production image
        run: |
          docker build \
            -f Dockerfile \
            -t cartify-be:latest \
            .

      - name: Push BE image
        run: |
          docker tag cartify-be:latest ${{ secrets.DOCKER_HUB_USERNAME }}/cartify-be:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cartify-be:latest
